package example.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static example.Laskuja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.24 14:19:31 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LaskujaTest {



  // Generated by ComTest BEGIN
  /** testSumma9 */
  @Test
  public void testSumma9() {    // Laskuja: 9
    assertEquals("From: Laskuja line: 10", 5, summa(2,3)); 
    assertEquals("From: Laskuja line: 11", 0, summa(-5,5)); 
  } // Generated by ComTest END
}