package demo.d2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d2.KertomaDoWhile.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.03 20:30:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KertomaDoWhileTest {



  // Generated by ComTest BEGIN
  /** testKertoma25 */
  @Test
  public void testKertoma25() {    // KertomaDoWhile: 25
    assertEquals("From: KertomaDoWhile line: 26", 1, kertoma(0)); 
    assertEquals("From: KertomaDoWhile line: 27", 1, kertoma(1)); 
    assertEquals("From: KertomaDoWhile line: 28", 2, kertoma(2)); 
    assertEquals("From: KertomaDoWhile line: 29", 6, kertoma(3)); 
    assertEquals("From: KertomaDoWhile line: 30", 24, kertoma(4)); 
    assertEquals("From: KertomaDoWhile line: 31", 120, kertoma(5)); 
    assertEquals("From: KertomaDoWhile line: 32", 720, kertoma(6)); 
    assertEquals("From: KertomaDoWhile line: 33", 5040, kertoma(7)); 
    assertEquals("From: KertomaDoWhile line: 34", 40320, kertoma(8)); 
    assertEquals("From: KertomaDoWhile line: 35", 362880, kertoma(9)); 
    assertEquals("From: KertomaDoWhile line: 36", 3628800, kertoma(10)); 
  } // Generated by ComTest END
}