package demo.d2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d2.KertomaWhile.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.03 21:05:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KertomaWhileTest {


  // Generated by ComTest BEGIN
  /** testKertoma24 */
  @Test
  public void testKertoma24() {    // KertomaWhile: 24
    assertEquals("From: KertomaWhile line: 25", 1, kertoma(0)); 
    assertEquals("From: KertomaWhile line: 26", 1, kertoma(1)); 
    assertEquals("From: KertomaWhile line: 27", 2, kertoma(2)); 
    assertEquals("From: KertomaWhile line: 28", 6, kertoma(3)); 
    assertEquals("From: KertomaWhile line: 29", 24, kertoma(4)); 
    assertEquals("From: KertomaWhile line: 30", 120, kertoma(5)); 
    assertEquals("From: KertomaWhile line: 31", 720, kertoma(6)); 
    assertEquals("From: KertomaWhile line: 32", 5040, kertoma(7)); 
    assertEquals("From: KertomaWhile line: 33", 40320, kertoma(8)); 
    assertEquals("From: KertomaWhile line: 34", 362880, kertoma(9)); 
    assertEquals("From: KertomaWhile line: 35", 3628800, kertoma(10)); 
  } // Generated by ComTest END
}