package demo.d11.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.FunktionMinimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.19 12:52:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunktionMinimiTest {



  // Generated by ComTest BEGIN
  /** testFunMin91 */
  @Test
  public void testFunMin91() {    // FunktionMinimi: 91
    assertEquals("From: FunktionMinimi line: 92", 1.0, funMin((x) -> x*x + 1 , 0, 3, 10), 0.000001); 
    assertEquals("From: FunktionMinimi line: 93", 2.0, funMin((x) -> x*x + 2 , 0, 3, 10), 0.000001); 
    assertEquals("From: FunktionMinimi line: 94", -3.0*3.0+1, funMin((x) -> -x*x + 1 , 0, 3, 1000), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testFunMin113 */
  @Test
  public void testFunMin113() {    // FunktionMinimi: 113
    assertEquals("From: FunktionMinimi line: 114", 1.0, funMin((x) -> x*x + 1 , 0, 3), 0.000001); 
    assertEquals("From: FunktionMinimi line: 115", 2.0, funMin((x) -> x*x + 2 , 0, 3), 0.000001); 
    assertEquals("From: FunktionMinimi line: 116", -13.0*3.0+1, funMin((x) -> -x*x + 1 , 0, 3), 0.000001); 
  } // Generated by ComTest END
}