package demo.d11.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.Sin.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.19 13:48:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SinTest {



  // Generated by ComTest BEGIN
  /** testFunMin42 */
  @Test
  public void testFunMin42() {    // Sin: 42
    assertEquals("From: Sin line: 43", 1.0, funMin((x) -> x*x + 1 , 0, 3, 0.5), 0.000001); 
    assertEquals("From: Sin line: 44", 2.0, funMin((x) -> x*x + 2 , 0, 3, 0.5), 0.000001); 
    assertEquals("From: Sin line: 45", -3.0*3.0+1, funMin((x) -> -x*x + 1 , 0, 3, 0.5), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testFunMax64 */
  @Test
  public void testFunMax64() {    // Sin: 64
    assertEquals("From: Sin line: 65", 11.0, funMax((x) -> x*x + 1 , 0, 3, 0.5), 0.000001); 
    assertEquals("From: Sin line: 66", 11.0, funMax((x) -> x*x + 2 , 0, 3, 0.5), 0.000001); 
    assertEquals("From: Sin line: 67", 1.0, funMax((x) -> -x*x + 1 , 0, 3, 0.5), 0.000001); 
  } // Generated by ComTest END
}