package demo.d11.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.Vaihtaminen.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.22 18:51:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VaihtaminenTest {



  // Generated by ComTest BEGIN
  /** testKaanna55 */
  @Test
  public void testKaanna55() {    // Vaihtaminen: 55
    int[] t = { 2, 32, 76, 62, 31, 86} ; 
    kaanna(t); 
    assertEquals("From: Vaihtaminen line: 59", "[86, 31, 62, 76, 32, 2]", Arrays.toString(t)); 
    int[] t2 = { 2, 32, 76, 62, 31, 86, 99} ; 
    kaanna(t2); 
    assertEquals("From: Vaihtaminen line: 62", "[99, 86, 31, 62, 76, 32, 2]", Arrays.toString(t2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaJokaToinen83 */
  @Test
  public void testVaihdaJokaToinen83() {    // Vaihtaminen: 83
    int[] t = { 2, 32, 76, 62, 31, 86} ; 
    vaihdaJokaToinen(t); 
    assertEquals("From: Vaihtaminen line: 87", "[32, 2, 62, 76, 86, 31]", Arrays.toString(t)); 
    int[] t2 = { 2, 32, 76, 62, 31, 86, 99} ; 
    vaihdaJokaToinen(t2); 
    assertEquals("From: Vaihtaminen line: 90", "[32, 2, 62, 76, 86, 31, 99]", Arrays.toString(t2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaParillisissaPaikoissa111 */
  @Test
  public void testSummaParillisissaPaikoissa111() {    // Vaihtaminen: 111
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 113", 9, summaParillisissaPaikoissa(t)); 
    assertEquals("From: Vaihtaminen line: 114", 3, summaParillisissaPaikoissa(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 115", 0, summaParillisissaPaikoissa(new int[]{})); 
    assertEquals("From: Vaihtaminen line: 116", 1, summaParillisissaPaikoissa(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 117", 1, summaParillisissaPaikoissa(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 118", 4, summaParillisissaPaikoissa(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma140 */
  @Test
  public void testSumma140() {    // Vaihtaminen: 140
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 142", 21, summa(t)); 
    assertEquals("From: Vaihtaminen line: 143", 6, summa(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 144", 0, summa(new int[]{})); 
    assertEquals("From: Vaihtaminen line: 145", 1, summa(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 146", 3, summa(new int[]{1,2})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaPerattaistenErotuksista162 */
  @Test
  public void testSummaPerattaistenErotuksista162() {    // Vaihtaminen: 162
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 164", -3, summaPerattaistenErotuksista(t)); 
    assertEquals("From: Vaihtaminen line: 165", 0, summaPerattaistenErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 166", 0, summaPerattaistenErotuksista(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 167", -1, summaPerattaistenErotuksista(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 168", -1, summaPerattaistenErotuksista(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaVastaavienErotuksista190 */
  @Test
  public void testSummaVastaavienErotuksista190() {    // Vaihtaminen: 190
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 192", -9, summaVastaavienErotuksista(t)); 
    assertEquals("From: Vaihtaminen line: 193", 0, summaVastaavienErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 194", 0, summaVastaavienErotuksista(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 195", -1, summaVastaavienErotuksista(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 196", -2, summaVastaavienErotuksista(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaArvoihin218 */
  @Test
  public void testLisaaArvoihin218() {    // Vaihtaminen: 218
    int[] t = { 1,2,3,4,5,6} ; 
    lisaaArvoihin(t,5); 
    assertEquals("From: Vaihtaminen line: 222", "[6, 7, 8, 9, 10, 11]", Arrays.toString(t)); 
    assertEquals("From: Vaihtaminen line: 223", "[]", Arrays.toString(lisaaArvoihin(new int[]{},5))); 
    assertEquals("From: Vaihtaminen line: 224", "[6]", Arrays.toString(lisaaArvoihin(new int[]{1},5))); 
    assertEquals("From: Vaihtaminen line: 225", "[4, 5]", Arrays.toString(lisaaArvoihin(new int[]{1,2},3))); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskePerakkaiset249 */
  @Test
  public void testLaskePerakkaiset249() {    // Vaihtaminen: 249
    int[] t = { 1,2,3,4,5,6} ; 
    laskePerakkaiset(t); 
    assertEquals("From: Vaihtaminen line: 253", "[3, 0, 7, 0, 11, 0]", Arrays.toString(t)); 
    assertEquals("From: Vaihtaminen line: 254", "[]", Arrays.toString(laskePerakkaiset(new int[]{}))); 
    assertEquals("From: Vaihtaminen line: 255", "[1]", Arrays.toString(laskePerakkaiset(new int[]{1}))); 
    assertEquals("From: Vaihtaminen line: 256", "[3, 0]", Arrays.toString(laskePerakkaiset(new int[]{1,2}))); 
    assertEquals("From: Vaihtaminen line: 257", "[3, 0, 3]", Arrays.toString(laskePerakkaiset(new int[]{1,2,3}))); 
  } // Generated by ComTest END
}