package astia.test;
// Generated by ComTest BEGIN
import astia.*;
import fi.jyu.mit.ohj2.Suuntaaja;
import static org.junit.Assert.*;
import org.junit.*;
import static astia.AstiaPeli.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.20 12:50:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AstiaPeliTest {



  // Generated by ComTest BEGIN
  /** testEtsi62 */
  @Test
  public void testEtsi62() {    // AstiaPeli: 62
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 64", 500000000, peli.etsi("ä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testNimiOhje79 */
  @Test
  public void testNimiOhje79() {    // AstiaPeli: 79
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    peli.nimiOhje("5", "ä");  // Ei tarpeeksi astioita pelaamiseen
    assertEquals("From: AstiaPeli line: 84", null, so.ero("")); 
    peli.nimiOhje("a", "b");  // Ei tarpeeksi astioita, väärät nimet
    assertEquals("From: AstiaPeli line: 86", null, so.ero("")); 
    peli.lisaa_astia("8",8); 
    peli.nimiOhje("ä", "8");  // Normaali tapaus
    assertEquals("From: AstiaPeli line: 89", null, so.ero("Käytössä olevat nimet: ä, 5, 8.\n")); 
    peli.nimiOhje("a", "8");  // Väärä nimi
    String tulos = "Käytössä olevat nimet: ä, 5, 8.\n" +
    "a ei ole validi nimi.\n"; 
    assertEquals("From: AstiaPeli line: 93", null, so.ero(tulos)); 
    peli.nimiOhje("a", "kasi");  // Kummatkin nimet vääriä
    tulos = "Käytössä olevat nimet: ä, 5, 8.\n" +
    "a ei ole validi nimi.\n" +
    "kasi ei ole validi nimi.\n"; 
    assertEquals("From: AstiaPeli line: 98", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta_ohje118 */
  @Test
  public void testTulosta_ohje118() {    // AstiaPeli: 118
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    peli.tulosta_ohje(); 
    assertEquals("From: AstiaPeli line: 123", null, so.ero("Ei tarpeeksi astioita pelaamiseen. Tarvitaan vähintään 2 astiaa.\n")); 
    peli.lisaa_astia("8",8); 
    peli.tulosta_ohje(); 
    assertEquals("From: AstiaPeli line: 126", null, so.ero("Käytössäsi on 8 ja 5 litran astia ja Ämpäri (100.0 l)\n")); 
    peli.lisaa_astia("4",4.5); 
    peli.tulosta_ohje(); 
    assertEquals("From: AstiaPeli line: 129", null, so.ero("Käytössäsi on 4.5, 8 ja 5 litran astia ja Ämpäri (100.0 l)\n")); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPelaa153 */
  @Test
  public void testPelaa153() {    // AstiaPeli: 153
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    peli.lisaa_astia("8",8); 
    peli.pelaa(); 
    String tulos =
    "5.0 litran astiassa on 0.0 litraa nestettä\n" +
    "8.0 litran astiassa on 0.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >\n"; 
    assertEquals("From: AstiaPeli line: 163", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMain193 */
  @Test
  public void testMain193() {    // AstiaPeli: 193
    Suuntaaja.StringInput si = new Suuntaaja.StringInput(""); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    si.input("ä 8\n8 5\n4 5\n\n"); 
    main(null); 
    String tulos =
    "Käytössäsi on 8 ja 5 litran astia ja Ämpäri (100.0 l)\n"+
    "5.0 litran astiassa on 0.0 litraa nestettä\n" +
    "8.0 litran astiassa on 0.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "5.0 litran astiassa on 0.0 litraa nestettä\n" +
    "8.0 litran astiassa on 8.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "5.0 litran astiassa on 5.0 litraa nestettä\n" +
    "8.0 litran astiassa on 3.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "Käytössä olevat nimet: ä, 5, 8.\n"            +
    "4 ei ole validi nimi.\n"                      +
    "5.0 litran astiassa on 5.0 litraa nestettä\n" +
    "8.0 litran astiassa on 3.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"; 
    assertEquals("From: AstiaPeli line: 216", null, so.ero(tulos)); 
    si.palauta(); so.palauta(); 
  } // Generated by ComTest END
}