package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.Suuntaaja;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d10.KirjaintenEsiintymat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.11 18:03:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaintenEsiintymatTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain18 
   * @throws IOException when error
   */
  @Test
  public void testMain18() throws IOException {    // KirjaintenEsiintymat: 18
    String tiednimi = "testiesiintymat.txt"; 
    VertaaTiedosto.kirjoitaTiedosto(tiednimi, "AaAkkostesti3\näöååå"); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    main(new String[]{tiednimi}); 
    so.palauta(); 
    String tulos = "a: 3\ne: 1\ni: 1\nk: 2\no: 1\ns: 2\nt: 2\nä: 1\nå: 3\nö: 1\n"; 
    assertEquals("From: KirjaintenEsiintymat line: 29", null, so.ero(tulos)); 
    VertaaTiedosto.tuhoaTiedosto(tiednimi); 
    Suuntaaja.StringOutput se = new Suuntaaja.StringOutput(true); 
    main(new String[]{"xxx.xxx"}); 
    se.palauta(); 
    { String _l_=se.toString(),_r_="(?s)"+"Tiedosto ei aukea! xxx\\.xxx .*"; if ( !_l_.matches(_r_) ) fail("From: KirjaintenEsiintymat line: 34" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}