package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.ByteArrayOutputStream;
import demo.d10.Koulu;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.11 23:40:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KouluTest {



  // Generated by ComTest BEGIN
  /** testLisaa59 */
  @Test
  public void testLisaa59() {    // Koulu: 59
    ByteArrayOutputStream bs  = new ByteArrayOutputStream(); 
    String alku =  "%n%nLuokka: 1b oppilaita: %d%n" +
    "==========================================%n"; 
    String loppu = "==========================================%n"; 
    String t = ""; 
    Koulu luokka = new Koulu("1b"); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 76", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Aku",5.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 77", String.format(alku+(t+="Ankka Aku              keskiarvo:  5.00%n")+loppu,1), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Tupu",7.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 78", String.format(alku+(t+="Ankka Tupu             keskiarvo:  7.00%n")+loppu,2), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Hiiri Mikki",9.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 79", String.format(alku+(t+="Hiiri Mikki            keskiarvo:  9.00%n")+loppu,3), bs.toString()); bs.reset();  
    luokka.poistaKaikki(); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 90", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Hiiri Mikki",9.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 91", String.format(alku+(t+="Hiiri Mikki            keskiarvo:  9.00%n")+loppu,1), bs.toString()); bs.reset();  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaKaikki106 */
  @Test
  public void testPoistaKaikki106() {    // Koulu: 106
    ByteArrayOutputStream bs  = new ByteArrayOutputStream(); 
    String alku =  "%n%nLuokka: 7a oppilaita: %d%n" +
    "==========================================%n"; 
    String loppu = "==========================================%n"; 
    String t = ""; 
    Koulu luokka = new Koulu("7a"); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 123", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Taavi",9.9)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 124", String.format(alku+(t+="Ankka Taavi            keskiarvo:  9.90%n")+loppu,1), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Roope",8.5)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 125", String.format(alku+(t+="Ankka Roope            keskiarvo:  8.50%n")+loppu,2), bs.toString()); bs.reset();  
    luokka.poistaKaikki(); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 131", String.format(alku+loppu,0), bs.toString()); bs.reset(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta144 */
  @Test
  public void testTulosta144() {    // Koulu: 144
    ByteArrayOutputStream bs  = new ByteArrayOutputStream(); 
    String alku =  "%n%nLuokka: 5c oppilaita: %d%n" +
    "==========================================%n"; 
    String loppu = "==========================================%n"; 
    String t = ""; 
    Koulu luokka = new Koulu("5c"); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 161", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Leenu",7.75)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 162", String.format(alku+(t+="Ankka Leenu            keskiarvo:  7.75%n")+loppu,1), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Liinu",8.25)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 163", String.format(alku+(t+="Ankka Liinu            keskiarvo:  8.25%n")+loppu,2), bs.toString()); bs.reset();  
  } // Generated by ComTest END
}