package demo.d10.test;
// Generated by ComTest BEGIN
import demo.d9.Int;
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d10.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.11 22:38:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukkoGenTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone94 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone94() throws CloneNotSupportedException {    // TaulukkoGen: 94
    TaulukkoGen<Int> luvut = new TaulukkoGen<Int>(20); 
    luvut.lisaa(new Int(0)); luvut.lisaa(new Int(2)); 
    luvut.lisaa(new Int(99)); 
    TaulukkoGen<Int> taul = luvut.clone(); 
    assertEquals("From: TaulukkoGen line: 101", "0,2,99", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 102", "0,2,99", taul.toString()); 
    luvut.get(1).set(3); 
    assertEquals("From: TaulukkoGen line: 104", "0,3,99", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 105", "0,2,99", taul.toString()); 
    luvut.lisaa(new Int(2)); luvut.lisaa(new Int(5)); 
    luvut.lisaa(new Int(2)); luvut.lisaa(new Int(6)); 
    assertEquals("From: TaulukkoGen line: 108", "0,3,99,2,5,2,6", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 109", "0,2,99", taul.toString()); 
    try {
    assertEquals("From: TaulukkoGen line: 110", 2, taul.get(3).intValue()); 
    fail("TaulukkoGen: 110 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    luvut.poista(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 112", "0,3,99,5,6", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 113", "0,2,99", taul.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista137 */
  @Test
  public void testPoista137() {    // TaulukkoGen: 137
    TaulukkoGen<Int> luvut = new TaulukkoGen<Int>(20); 
    luvut.lisaa(new Int(4)); luvut.lisaa(new Int(7)); luvut.lisaa(new Int(6)); 
    luvut.lisaa(new Int(3)); luvut.lisaa(new Int(6)); luvut.lisaa(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 146", 6, luvut.poista(new Int(8)));  
    assertEquals("From: TaulukkoGen line: 147", 4, luvut.poista(new Int(6)));  
    assertEquals("From: TaulukkoGen line: 148", 3, luvut.poista(new Int(4)));  
    assertEquals("From: TaulukkoGen line: 149", 2, luvut.poista(new Int(2)));  
    assertEquals("From: TaulukkoGen line: 150", 1, luvut.poista(new Int(7)));  
    assertEquals("From: TaulukkoGen line: 151", 0, luvut.poista(new Int(3)));  
    assertEquals("From: TaulukkoGen line: 152", 0, luvut.poista(new Int(3)));  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista156 */
  @Test
  public void testPoista156() {    // TaulukkoGen: 156
    TaulukkoGen<Int> luvut = new TaulukkoGen<Int>(20); 
    luvut.lisaa(new Int(4)); luvut.lisaa(new Int(7)); luvut.lisaa(new Int(6)); 
    luvut.lisaa(new Int(3)); luvut.lisaa(new Int(6)); luvut.lisaa(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 162", 6, luvut.poista(new Int(8))); assertEquals("From: TaulukkoGen line: 162", "4,7,6,3,6,2", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 163", 4, luvut.poista(new Int(6))); assertEquals("From: TaulukkoGen line: 163", "4,7,3,2", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 164", 3, luvut.poista(new Int(4))); assertEquals("From: TaulukkoGen line: 164", "7,3,2", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 165", 2, luvut.poista(new Int(2))); assertEquals("From: TaulukkoGen line: 165", "7,3", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 166", 1, luvut.poista(new Int(7))); assertEquals("From: TaulukkoGen line: 166", "3", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 167", 0, luvut.poista(new Int(3))); 
    assertEquals("From: TaulukkoGen line: 168", 0, luvut.poista(new Int(3))); 
  } // Generated by ComTest END
}