package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.Suuntaaja;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d10.TiedostonNumerointi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.11 16:23:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TiedostonNumerointiTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain20 
   * @throws IOException when error
   */
  @Test
  public void testMain20() throws IOException {    // TiedostonNumerointi: 20
    String tiednimi = "testikoe.txt"; 
    VertaaTiedosto.kirjoitaTiedosto(tiednimi,
    "123456789012345678901234567890123456789012345678901234567890\n" +
    "Kissa istuu puussa\n" +
    "ja ihmettelee\n" +
    "mualiman menoa"); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    main(new String[]{tiednimi}); 
    so.palauta(); 
    String tulos = "/* 01 "+ "*" + "/" + " 1234567890123456789012345678901234567890\n" +
    "/* 02 "+ "*" + "/" + " Kissa istuu puussa\n" +
    "/* 03 "+ "*" + "/" + " ja ihmettelee\n" +
    "/* 04 "+ "*" + "/" + " mualiman menoa\n"; 
    assertEquals("From: TiedostonNumerointi line: 38", null, so.ero(tulos)); 
    VertaaTiedosto.tuhoaTiedosto(tiednimi); 
    Suuntaaja.StringOutput se = new Suuntaaja.StringOutput(true); 
    main(new String[]{"xxx.xxx"}); 
    se.palauta(); 
    { String _l_=se.toString(),_r_="(?s)"+"Tiedosto ei aukea! xxx\\.xxx .*"; if ( !_l_.matches(_r_) ) fail("From: TiedostonNumerointi line: 43" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}