package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.Suuntaaja;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d10.TietyllaAlkavat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.11 17:24:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietyllaAlkavatTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain19 
   * @throws IOException when error
   */
  @Test
  public void testMain19() throws IOException {    // TietyllaAlkavat: 19
    String tiednimi = "testirivit.txt"; 
    VertaaTiedosto.kirjoitaTiedosto(tiednimi,
    "* hei\n"       +
    "** moi\n"      +
    "*** terve\n\n" +
    "asd\n"         +
    "**"); 
    Suuntaaja.StringInput si = new Suuntaaja.StringInput(""); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    si.input("**\n"); 
    main(new String[]{tiednimi}); 
    si.palauta(); so.palauta(); 
    String tulos =
    "Anna merkkijono, jolla alkavat rivit tulostetaan >** moi\n" +
    "*** terve\n" +
    "**\n"; 
    assertEquals("From: TietyllaAlkavat line: 40", null, so.ero(tulos)); 
    VertaaTiedosto.tuhoaTiedosto(tiednimi); 
    Suuntaaja.StringOutput se = new Suuntaaja.StringOutput(true); 
    si.input("**\n"); 
    main(new String[]{"xxx.xxx"}); 
    si.palauta(); se.palauta(); 
    { String _l_=se.toString(),_r_="(?s)"+"Tiedosto ei aukea! xxx\\.xxx .*"; if ( !_l_.matches(_r_) ) fail("From: TietyllaAlkavat line: 46" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}