package demo.d4.fx.test;
// Generated by ComTest BEGIN
import javafx.embed.swing.JFXPanel;
import javafx.scene.control.*;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.fx.IkaGUIController.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.13 12:57:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IkaGUIControllerTest {



  // Generated by ComTest BEGIN
  /** testHaeInt37 */
  @Test
  public void testHaeInt37() {    // IkaGUIController: 37
    (new JFXPanel()).toString(); 
    assertEquals("From: IkaGUIController line: 41", 234, haeInt(new TextField("234"), 44)); 
    assertEquals("From: IkaGUIController line: 42", 44, haeInt(new TextField("foobar1"), 44)); 
    assertEquals("From: IkaGUIController line: 43", 1, haeInt(new TextField("1foobar"), 44)); 
  } // Generated by ComTest END
}