package demo.d8.test;
// Generated by ComTest BEGIN
import java.util.Calendar;
import demo.d8.Pvm;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.08 16:20:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {

  // Generated by ComTest BEGIN  // Pvm: 19
   private static final String s22_2     = "22.2.2020",
                               s23_2     = "23.2.2020"; 
   private final Pvm    tammi2012 = new Pvm(1,1),
                        helmi2012 = new Pvm(1),
                        tanaan    = new Pvm(),
                        maalis97  = new Pvm(1,3,97),
                        p22_2     = new Pvm(s22_2),
                        p23_2     = new Pvm(s23_2); 
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPvm85 */
  @Test
  public void testPvm85() {    // Pvm: 85
    Calendar nyt = Calendar.getInstance(); 
    int pv = nyt.get(Calendar.DATE); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm; 
    pvm = new Pvm(1, 1); assertEquals("From: Pvm line: 96", "1.1."+vv, pvm.toString());  
    pvm = new Pvm(1); assertEquals("From: Pvm line: 97", 1+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(); assertEquals("From: Pvm line: 98", pv+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(1, 3, 97); assertEquals("From: Pvm line: 99", "1.3.1997", pvm.toString());  
    pvm = new Pvm("1.5"); assertEquals("From: Pvm line: 100", "1.5."+vv, pvm.toString());  
    pvm = new Pvm("1..1990"); assertEquals("From: Pvm line: 101", "1."+kk+".1990", pvm.toString());  
    pvm = new Pvm("..1990"); assertEquals("From: Pvm line: 102", pv+"."+kk+".1990", pvm.toString());  
  } // Generated by ComTest END
}