package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.27 16:06:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testMatriisinSuurin24 */
  @Test
  public void testMatriisinSuurin24() {    // Taulukot: 24
    double[][] matriisi = { { 3.3,  6.5, -1.5 } , { 0.0, 50.0, 23.1 } } ; 
    assertEquals("From: Taulukot line: 26", 50.0, matriisinSuurin(matriisi), 0.000001);  // normaali tapaus
    matriisi = new double[][]{ { 3.3, 60.5, -1.5 } , { 0.0, 50.0, 23.1 } } ; 
    assertEquals("From: Taulukot line: 28", 60.5, matriisinSuurin(matriisi), 0.000001);  // suurin ensimmäisellä rivillä
    matriisi = new double[][]{ { 3.3 } , { 0.0 } } ; 
    assertEquals("From: Taulukot line: 30", 3.3, matriisinSuurin(matriisi), 0.000001);  // eri kokoinen
    matriisi = new double[][]{ { -3.3, -2.1 } , { 0.0, -6.5 } } ; 
    assertEquals("From: Taulukot line: 32", 0.0, matriisinSuurin(matriisi), 0.000001);  // negatiiviset luvut
    matriisi = new double[][]{ { } , { } } ; 
    assertEquals("From: Taulukot line: 34", Double.MIN_VALUE, matriisinSuurin(matriisi), 0.000001);  // tyhjä
  } // Generated by ComTest END
}