package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Taulukot2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.27 16:22:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class Taulukot2Test {



  // Generated by ComTest BEGIN
  /** testSumma25 */
  @Test
  public void testSumma25() {    // Taulukot2: 25
    double[][] matriisi = { { 3.3,  6.5, -1.5 } , { 0.0, 50.0, 23.1 } } ; 
    assertEquals("From: Taulukot2 line: 27", 81.4, summa(matriisi), 0.000001);  // normaali tapaus
    matriisi = new double[][]{ { 3.3 } , { 0.0 } } ; 
    assertEquals("From: Taulukot2 line: 29", 3.3, summa(matriisi), 0.000001);  // eri kokoinen
    matriisi = new double[][]{ { -3.3, -2.1 } , { 0.0, -6.5 } } ; 
    assertEquals("From: Taulukot2 line: 31", -11.9, summa(matriisi), 0.000001);  // negatiiviset luvut
    matriisi = new double[][]{ { } , { } } ; 
    assertEquals("From: Taulukot2 line: 33", 0, summa(matriisi), 0.000001);  // tyhjä
  } // Generated by ComTest END
}