package demo.d5.test;
// Generated by ComTest BEGIN
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.15 16:46:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testToString32 */
  @Test
  public void testToString32() {    // Henkilo: 32
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 34", "Aku|Ankka|1934", aku.toString()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkilo line: 36", "Pele||1940", pele.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi49 */
  @Test
  public void testGetNimi49() {    // Henkilo: 49
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 51", "Aku Ankka", aku.getNimi()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkilo line: 53", "Pele", pele.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSyntymavuosi64 */
  @Test
  public void testGetSyntymavuosi64() {    // Henkilo: 64
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 66", 1934, aku.getSyntymavuosi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta78 */
  @Test
  public void testTulosta78() {    // Henkilo: 78
    ByteArrayOutputStream byteoutput = new ByteArrayOutputStream(); 
    Henkilo hlo = new Henkilo("Aku","Ankka",1934); 
    hlo.tulosta(byteoutput); 
    { String _l_=byteoutput.toString(),_r_="Aku Ankka 1934\\s*"; if ( !_l_.matches(_r_) ) fail("From: Henkilo line: 83" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse112 */
  @Test
  public void testParse112() {    // Henkilo: 112
    Henkilo aku = new Henkilo(); 
    aku.parse("Aku|Ankka|1934"); 
    assertEquals("From: Henkilo line: 115", "Aku|Ankka|1934", aku.toString()); 
    aku.parse("Aku|Ankka|"); 
    assertEquals("From: Henkilo line: 117", "Aku|Ankka|0", aku.toString()); 
    aku.parse("Ak"); 
    assertEquals("From: Henkilo line: 119", "Ak||0", aku.toString()); 
    aku.parse(""); 
    assertEquals("From: Henkilo line: 121", "||0", aku.toString()); 
  } // Generated by ComTest END
}