package demo.d5.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d5.Kasittele.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.15 15:56:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KasitteleTest {



  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko28 */
  @Test
  public void testKasitteleTaulukko28() {    // Kasittele: 28
    int[] t; 
    t = new int[]{55, 44, 33, 2, 5, 9}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 34", "[9, 5, 2, 33, 44, 55]", Arrays.toString(t));  
    t = new int[]{23, 45, 12, 9, 3, 7}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 35", "[7, 3, 9, 12, 45, 23]", Arrays.toString(t));  
    t = new int[]{1, 2, 3, 4, 5}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 36", "[5, 4, 3, 2, 1]", Arrays.toString(t));  
    t = new int[]{1}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 37", "[1]", Arrays.toString(t));  
    t = new int[]{1, 2}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 38", "[2, 1]", Arrays.toString(t));  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko254 */
  @Test
  public void testKasitteleTaulukko254() {    // Kasittele: 54
    int[] t; 
    t = new int[]{55, 44, 33, 2, 5, 9}; KasitteleTaulukko2(t); assertEquals("From: Kasittele line: 60", "[44, 55, 2, 33, 9, 5]", Arrays.toString(t));  
    t = new int[]{23, 45, 12, 9, 3, 7}; KasitteleTaulukko2(t); assertEquals("From: Kasittele line: 61", "[45, 23, 9, 12, 7, 3]", Arrays.toString(t));  
    t = new int[]{1, 2, 3, 4, 5}; KasitteleTaulukko2(t); assertEquals("From: Kasittele line: 62", "[2, 1, 4, 3, 5]", Arrays.toString(t));  
    t = new int[]{1}; KasitteleTaulukko2(t); assertEquals("From: Kasittele line: 63", "[1]", Arrays.toString(t));  
    t = new int[]{1, 2}; KasitteleTaulukko2(t); assertEquals("From: Kasittele line: 64", "[2, 1]", Arrays.toString(t));  
  } // Generated by ComTest END
}