package demo.d5.test;
// Generated by ComTest BEGIN
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.15 19:21:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LinjaAutoTest {



  // Generated by ComTest BEGIN
  /** testLinjaAuto20 */
  @Test
  public void testLinjaAuto20() {    // LinjaAuto: 20
    LinjaAuto linkki = new LinjaAuto(42); 
    assertEquals("From: LinjaAuto line: 22", 42, linkki.getTilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLinjaAuto33 */
  @Test
  public void testLinjaAuto33() {    // LinjaAuto: 33
    LinjaAuto linkki = new LinjaAuto(); 
    assertEquals("From: LinjaAuto line: 35", 0, linkki.getTilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta46 */
  @Test
  public void testTulosta46() {    // LinjaAuto: 46
    ByteArrayOutputStream byteoutput = new ByteArrayOutputStream(); 
    LinjaAuto linkki = new LinjaAuto(42); 
    linkki.tulosta(byteoutput); 
    { String _l_=byteoutput.toString(),_r_="42,0,42\\s*"; if ( !_l_.matches(_r_) ) fail("From: LinjaAuto line: 51" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTilaa63 */
  @Test
  public void testGetTilaa63() {    // LinjaAuto: 63
    LinjaAuto linkki = new LinjaAuto(42); 
    assertEquals("From: LinjaAuto line: 65", 42, linkki.getTilaa()); 
    linkki.lisaa(5); 
    assertEquals("From: LinjaAuto line: 67", 37, linkki.getTilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTilaa78 */
  @Test
  public void testTilaa78() {    // LinjaAuto: 78
    LinjaAuto linkki = new LinjaAuto(42); 
    assertEquals("From: LinjaAuto line: 80", true, linkki.tilaa()); 
    linkki.lisaa(50); 
    assertEquals("From: LinjaAuto line: 82", false, linkki.tilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa95 */
  @Test
  public void testLisaa95() {    // LinjaAuto: 95
    LinjaAuto linkki = new LinjaAuto(42); 
    int yli = linkki.lisaa(50); 
    assertEquals("From: LinjaAuto line: 98", 0, linkki.getTilaa()); 
    assertEquals("From: LinjaAuto line: 99", 8, yli); 
    int ali = linkki.lisaa(-50); 
    assertEquals("From: LinjaAuto line: 101", 42, linkki.getTilaa()); 
    assertEquals("From: LinjaAuto line: 102", -8, ali); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna115 */
  @Test
  public void testVahenna115() {    // LinjaAuto: 115
    LinjaAuto linkki = new LinjaAuto(42); 
    int ali = linkki.vahenna(50); 
    assertEquals("From: LinjaAuto line: 118", 42, linkki.getTilaa()); 
    assertEquals("From: LinjaAuto line: 119", -50, ali); 
    linkki.lisaa(30); 
    linkki.vahenna(8); 
    assertEquals("From: LinjaAuto line: 122", 20, linkki.getTilaa()); 
    int yli = linkki.vahenna(-30); 
    assertEquals("From: LinjaAuto line: 124", 0, linkki.getTilaa()); 
    assertEquals("From: LinjaAuto line: 125", 10, yli); 
  } // Generated by ComTest END
}