package demo.d5.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.15 17:02:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testToString83 */
  @Test
  public void testToString83() {    // Pvm: 83
    Pvm pvm = new Pvm(10,2,2008); 
    assertEquals("From: Pvm line: 85", "10.2.2008", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse98 */
  @Test
  public void testParse98() {    // Pvm: 98
    Pvm pvm = new Pvm(); 
    pvm.parse("11.05.02"); assertEquals("From: Pvm line: 100", "11.5.2002", pvm.toString()); 
    pvm.parse("11.05.97"); assertEquals("From: Pvm line: 101", "11.5.1997", pvm.toString()); 
    pvm.parse("17.3"); assertEquals("From: Pvm line: 102", "17.3.1997", pvm.toString()); 
    pvm.parse("19"); assertEquals("From: Pvm line: 103", "19.3.1997", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPv130 */
  @Test
  public void testGetPv130() {    // Pvm: 130
    Pvm pvm = new Pvm(); 
    assertEquals("From: Pvm line: 132", 30, pvm.getPv()); 
    pvm.parse("3.4"); 
    assertEquals("From: Pvm line: 134", 3, pvm.getPv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKk145 */
  @Test
  public void testGetKk145() {    // Pvm: 145
    Pvm pvm = new Pvm(); 
    assertEquals("From: Pvm line: 147", 1, pvm.getKk()); 
    pvm.parse("3.4"); 
    assertEquals("From: Pvm line: 149", 4, pvm.getKk()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVv160 */
  @Test
  public void testGetVv160() {    // Pvm: 160
    Pvm pvm = new Pvm(); 
    assertEquals("From: Pvm line: 162", 2012, pvm.getVv()); 
    pvm.parse("3.4"); 
    assertEquals("From: Pvm line: 164", 2012, pvm.getVv()); 
    pvm.parse("3.4.1"); 
    assertEquals("From: Pvm line: 166", 2001, pvm.getVv()); 
  } // Generated by ComTest END
}