.PHONY: clean All

All:
	@echo "----------Building project:[ demo2 - Debug ]----------"
	@cd "demo2" && "$(MAKE)" -f  "demo2.mk"
clean:
	@echo "----------Cleaning project:[ demo2 - Debug ]----------"
	@cd "demo2" && "$(MAKE)" -f  "demo2.mk" clean
