package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Postimaksu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.23 20:49:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PostimaksuTest {



  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPaino23 */
  @Test
  public void testSuurinKirjeenPaino23() {    // Postimaksu: 23
    double[][] postimaksut = {   {1.00,  1.40,   2.00,   4.00,   6.00,   10.00},
    { 50,    100,    250,    500,    1000,   2000} } ; 
    assertEquals("From: Postimaksu line: 26", 250, suurinKirjeenPaino(2.05, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 27", 2000, suurinKirjeenPaino(20.00, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 28", 2000, suurinKirjeenPaino(21.00, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 29", 0, suurinKirjeenPaino(0.00, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 30", 0, suurinKirjeenPaino(0.99, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 31", 0, suurinKirjeenPaino(-1, postimaksut), 0.000001); 
    postimaksut[0][0] = 0;  // {{0, 1.40, 2.00, 4.00, 6.00, 10.00}, {50, 100, 250, 500, 1000, 2000}}
    assertEquals("From: Postimaksu line: 33", 50, suurinKirjeenPaino(1.39, postimaksut), 0.000001); 
    assertEquals("From: Postimaksu line: 34", 0, suurinKirjeenPaino(-1, postimaksut), 0.000001); 
    postimaksut[0][0] = -1;  // {{-1, 1.40, 2.00, 4.00, 6.00, 10.00}, {50, 100, 250, 500, 1000, 2000}}
    assertEquals("From: Postimaksu line: 36", 50, suurinKirjeenPaino(-1, postimaksut), 0.000001);  // Futureproofattu antirahan käyttöönottoa varten
    double[][] tyhja = { } ; 
    assertEquals("From: Postimaksu line: 38", 0, suurinKirjeenPaino(2.05, tyhja), 0.000001); 
    double[][] vajaa = {   {1.00,  1.40,   2.00,   4.00,   6.00,   10.00},
    { 50,    100,    250                          } } ; 
    assertEquals("From: Postimaksu line: 41", 250, suurinKirjeenPaino(2.05, vajaa), 0.000001); 
    assertEquals("From: Postimaksu line: 42", 250, suurinKirjeenPaino(20.00, vajaa), 0.000001); 
    double[][] vajaa2 = {  {1.00,  1.40,   2.00,                       },
    { 50,    100,    250,    500,    1000,   2000} } ; 
    assertEquals("From: Postimaksu line: 45", 250, suurinKirjeenPaino(2.05, vajaa2), 0.000001); 
    assertEquals("From: Postimaksu line: 46", 250, suurinKirjeenPaino(20.00, vajaa2), 0.000001); 
  } // Generated by ComTest END
}