package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.TaulukonSummia.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.23 19:09:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukonSummiaTest {



  // Generated by ComTest BEGIN
  /** testSummaPerattaistenErotuksista35 */
  @Test
  public void testSummaPerattaistenErotuksista35() {    // TaulukonSummia: 35
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: TaulukonSummia line: 37", -3, summaPerattaistenErotuksista(t)); 
    assertEquals("From: TaulukonSummia line: 38", 0, summaPerattaistenErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: TaulukonSummia line: 39", 1, summaPerattaistenErotuksista(new int[]{1,1,1,1,1})); 
    assertEquals("From: TaulukonSummia line: 40", 1, summaPerattaistenErotuksista(new int[]{1})); 
    assertEquals("From: TaulukonSummia line: 41", 0, summaPerattaistenErotuksista(new int[]{})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaVastaavienErotuksista58 */
  @Test
  public void testSummaVastaavienErotuksista58() {    // TaulukonSummia: 58
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: TaulukonSummia line: 60", -9, summaVastaavienErotuksista(t)); 
    assertEquals("From: TaulukonSummia line: 61", 0, summaVastaavienErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: TaulukonSummia line: 62", 0, summaVastaavienErotuksista(new int[]{1,1,1,1,1}));  // Keskimmäinen ei tule laskuun
    assertEquals("From: TaulukonSummia line: 63", -1, summaVastaavienErotuksista(new int[]{2,3})); 
    assertEquals("From: TaulukonSummia line: 64", 0, summaVastaavienErotuksista(new int[]{1})); 
    assertEquals("From: TaulukonSummia line: 65", 0, summaVastaavienErotuksista(new int[]{})); 
  } // Generated by ComTest END
}