package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.23 22:28:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testParas30 */
  @Test
  public void testParas30() {    // Taulukot: 30
    assertEquals("From: Taulukot line: 31", 7, paras(new double[]{5, 7, 3, 2, 1}), 0.000001); 
    assertEquals("From: Taulukot line: 32", 5.65, paras(new double[]{5.5, 5.6, 5.65}), 0.000001); 
    assertEquals("From: Taulukot line: 33", 1, paras(new double[]{1}), 0.000001); 
    assertEquals("From: Taulukot line: 34", -1, paras(new double[]{-5, -7, -3, -2, -1}), 0.000001); 
    assertEquals("From: Taulukot line: 35", 0, paras(new double[]{}), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHuonoin54 */
  @Test
  public void testHuonoin54() {    // Taulukot: 54
    assertEquals("From: Taulukot line: 55", 1, huonoin(new double[]{5, 7, 3, 2, 1}), 0.000001); 
    assertEquals("From: Taulukot line: 56", 5.5, huonoin(new double[]{5.5, 5.6, 5.65}), 0.000001); 
    assertEquals("From: Taulukot line: 57", 1, huonoin(new double[]{1}), 0.000001); 
    assertEquals("From: Taulukot line: 58", -7, huonoin(new double[]{-5, -7, -3, -2, -1}), 0.000001); 
    assertEquals("From: Taulukot line: 59", 0, huonoin(new double[]{}), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma78 */
  @Test
  public void testSumma78() {    // Taulukot: 78
    assertEquals("From: Taulukot line: 79", 18, summa(new double[]{5, 7, 3, 2, 1}), 0.000001); 
    assertEquals("From: Taulukot line: 80", 16.75, summa(new double[]{5.5, 5.6, 5.65}), 0.000001); 
    assertEquals("From: Taulukot line: 81", 1, summa(new double[]{1}), 0.000001); 
    assertEquals("From: Taulukot line: 82", -18, summa(new double[]{-5, -7, -3, -2, -1}), 0.000001); 
    assertEquals("From: Taulukot line: 83", 0, summa(new double[]{}), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaHuonoinJaParasPois101 */
  @Test
  public void testSummaHuonoinJaParasPois101() {    // Taulukot: 101
    assertEquals("From: Taulukot line: 102", 10, summaHuonoinJaParasPois(new double[]{5, 7, 3, 2, 1}), 0.000001); 
    assertEquals("From: Taulukot line: 103", 16.75, summaHuonoinJaParasPois(new double[]{5.5, 5.6, 5.65, 5.76, 4.43}), 0.000001); 
    assertEquals("From: Taulukot line: 104", 2, summaHuonoinJaParasPois(new double[]{1,2,3}), 0.000001); 
    assertEquals("From: Taulukot line: 105", 0, summaHuonoinJaParasPois(new double[]{1,2}), 0.000001); 
    assertEquals("From: Taulukot line: 106", 0, summaHuonoinJaParasPois(new double[]{1}), 0.000001); 
    assertEquals("From: Taulukot line: 107", -10, summaHuonoinJaParasPois(new double[]{-5, -7, -3, -2, -1}), 0.000001); 
    assertEquals("From: Taulukot line: 108", 0, summaHuonoinJaParasPois(new double[]{}), 0.000001); 
  } // Generated by ComTest END
}