package demo.d1.test;
// Generated by ComTest BEGIN
import java.util.List;
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d1.Kombinaatiot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.30 20:52:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KombinaatiotTest {


  // Generated by ComTest BEGIN
  /** testList55 */
  @Test
  public void testList55() {    // Kombinaatiot: 55
    List<String> valinnat = Arrays.asList("a","b","c"); 
    List<List<String>> kombit = etsiKombinaatiot(2,valinnat); 
    int i=0; 
    assertEquals("From: Kombinaatiot line: 60", "[a, a]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 61", "[a, b]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 62", "[a, c]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 63", "[b, a]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 64", "[b, b]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 65", "[b, c]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 66", "[c, a]", kombit.get(i++).toString()); 
    assertEquals("From: Kombinaatiot line: 67", 9, kombit.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasvata92 */
  @Test
  public void testKasvata92() {    // Kombinaatiot: 92
    int[] num = new int[2]; 
    assertEquals("From: Kombinaatiot line: 95", "[0, 0]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 95", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 96", "[0, 1]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 96", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 97", "[0, 2]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 97", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 98", "[1, 0]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 98", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 99", "[1, 1]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 99", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 100", "[1, 2]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 100", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 101", "[2, 0]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 101", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 102", "[2, 1]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 102", true, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 103", "[2, 2]", Arrays.toString(num)); assertEquals("From: Kombinaatiot line: 103", false, kasvata(num,3)); 
    assertEquals("From: Kombinaatiot line: 104", "[0, 0]", Arrays.toString(num)); 
  } // Generated by ComTest END
}