package tilaajat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tilaajat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.24 18:06:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PostiosoiteTest {



  // Generated by ComTest BEGIN
  /** testGetPostinumero61 */
  @Test
  public void testGetPostinumero61() {    // Postiosoite: 61
    Postiosoite helsinki = new Postiosoite(); 
    assertEquals("From: Postiosoite line: 63", 0, helsinki.getPostinumero()); 
    helsinki = new Postiosoite(10); 
    assertEquals("From: Postiosoite line: 65", 10, helsinki.getPostinumero()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPostitoimipaikka76 */
  @Test
  public void testGetPostitoimipaikka76() {    // Postiosoite: 76
    Postiosoite helsinki = new Postiosoite(); 
    assertEquals("From: Postiosoite line: 78", "", helsinki.getPostitoimipaikka()); 
    helsinki.taytaHelsinkiTiedoilla(); 
    { String _l_=helsinki.getPostitoimipaikka(),_r_="HELSINKI.*"; if ( !_l_.matches(_r_) ) fail("From: Postiosoite line: 80" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString122 */
  @Test
  public void testToString122() {    // Postiosoite: 122
    Postiosoite helsinki = new Postiosoite("00010", "HELSINKI"); 
    assertEquals("From: Postiosoite line: 124", "00010|HELSINKI", helsinki.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse136 */
  @Test
  public void testParse136() {    // Postiosoite: 136
    Postiosoite postiosoite = new Postiosoite(); 
    postiosoite.parse("   02020   |  METSÄ   "); 
    assertEquals("From: Postiosoite line: 139", 2020, postiosoite.getPostinumero()); 
    assertEquals("From: Postiosoite line: 140", "METSÄ", postiosoite.getPostitoimipaikka()); 
    assertEquals("From: Postiosoite line: 141", "02020|METSÄ", postiosoite.toString()); 
    postiosoite.parse("500|"); 
    assertEquals("From: Postiosoite line: 144", "00500|METSÄ", postiosoite.toString());  // Postitoimipaikka ei vaihdu tyhjäksi
  } // Generated by ComTest END
}