package alkuluku.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static alkuluku.Alkuluku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.01 15:11:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlkulukuTest {



  // Generated by ComTest BEGIN
  /** testMillaJaollinen28 */
  @Test
  public void testMillaJaollinen28() {    // Alkuluku: 28
    assertEquals("From: Alkuluku line: 29", 1, millaJaollinen(2)); 
    assertEquals("From: Alkuluku line: 30", 5, millaJaollinen(25)); 
    assertEquals("From: Alkuluku line: 31", 1, millaJaollinen(23)); 
    assertEquals("From: Alkuluku line: 32", 1, millaJaollinen(7)); 
  } // Generated by ComTest END
}