package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d6.TaulukonKasittely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.19 23:49:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukonKasittelyTest {



  // Generated by ComTest BEGIN
  /** testPienimmanPaikka15 */
  @Test
  public void testPienimmanPaikka15() {    // TaulukonKasittely: 15
    int[] t = { 4, 2, 1, 0, 3} ; 
    assertEquals("From: TaulukonKasittely line: 17", 3, pienimmanPaikka(t)); 
    int[] t2 = { 4, 2, -1, 0, 3} ; 
    assertEquals("From: TaulukonKasittely line: 19", 2, pienimmanPaikka(t2)); 
    int[] t3 = { } ; 
    assertEquals("From: TaulukonKasittely line: 21", -1, pienimmanPaikka(t3)); 
    int[] t4 = { 5} ; 
    assertEquals("From: TaulukonKasittely line: 23", 0, pienimmanPaikka(t4)); 
    int[] t5 = { 5, 5, 5, 5} ; 
    assertEquals("From: TaulukonKasittely line: 25", 0, pienimmanPaikka(t5)); 
    int[] t6 = { 5, 6, 5, 5} ; 
    assertEquals("From: TaulukonKasittely line: 27", 0, pienimmanPaikka(t6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPienin46 */
  @Test
  public void testPienin46() {    // TaulukonKasittely: 46
    int[] t = { 4, 2, 1, 0, 3} ; 
    assertEquals("From: TaulukonKasittely line: 48", 0, pienin(t)); 
    int[] t2 = { 4, 2, -1, 0, 3} ; 
    assertEquals("From: TaulukonKasittely line: 50", -1, pienin(t2)); 
    int[] t3 = { } ; 
    assertEquals("From: TaulukonKasittely line: 52", Integer.MAX_VALUE, pienin(t3)); 
    int[] t4 = { 5} ; 
    assertEquals("From: TaulukonKasittely line: 54", 5, pienin(t4)); 
    int[] t5 = { 5, 5, 5, 5} ; 
    assertEquals("From: TaulukonKasittely line: 56", 5, pienin(t5)); 
    int[] t6 = { 5, 6, 5, 5} ; 
    assertEquals("From: TaulukonKasittely line: 58", 5, pienin(t6)); 
  } // Generated by ComTest END
}