package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d9.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.13 16:09:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class EhdokasTest {



  // Generated by ComTest BEGIN
  /** testOsta42 */
  @Test
  public void testOsta42() {    // Ehdokas: 42
    Ehdokas ehd1 = new Ehdokas(100000.0,0); 
    { String _l_=ehd1.toString(),_r_="Rahaa 100000[.,]00, ääniä 0"; if ( !_l_.matches(_r_) ) fail("From: Ehdokas line: 44" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
    assertEquals("From: Ehdokas line: 45", true, ehd1.osta(200,100.0));  // Ostetaan sopivasti 
    { String _l_=ehd1.toString(),_r_="Rahaa 80000[.,]00, ääniä 200"; if ( !_l_.matches(_r_) ) fail("From: Ehdokas line: 46" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
    assertEquals("From: Ehdokas line: 47", false, ehd1.osta(200,1000.0));  // Ostetaan liian kallista
    { String _l_=ehd1.toString(),_r_="Rahaa 80000[.,]00, ääniä 200"; if ( !_l_.matches(_r_) ) fail("From: Ehdokas line: 48" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo64 */
  @Test
  public void testCompareTo64() {    // Ehdokas: 64
    Ehdokas ehd1 = new Ehdokas(100000.0,0),ehd2 = new Ehdokas(20000.0,300); 
    assertEquals("From: Ehdokas line: 66", true, ehd1.compareTo(ehd2) <  0); 
    assertEquals("From: Ehdokas line: 67", true, ehd2.compareTo(ehd1) >  0); 
    ehd1.osta(300,10); 
    assertEquals("From: Ehdokas line: 69", true, ehd2.compareTo(ehd1) == 0); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString79 */
  @Test
  public void testToString79() {    // Ehdokas: 79
    Ehdokas trump = new Ehdokas(1000000, 100); 
    { String _l_=trump.toString(),_r_="Rahaa 1000000[,.]00, ääniä 100"; if ( !_l_.matches(_r_) ) fail("From: Ehdokas line: 81" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}