package demo.d9.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d9.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.04 16:11:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukkoTest {



  // Generated by ComTest BEGIN
  /** 
   * testTaulukko8 
   * @throws Taulukko.TaulukkoTaysiException when error
   */
  @Test
  public void testTaulukko8() throws Taulukko.TaulukkoTaysiException {    // Taulukko: 8
    Taulukko luvut = new Taulukko(); 
    luvut.lisaa(0); luvut.lisaa(2); luvut.lisaa(99); 
    assertEquals("From: Taulukko line: 12", "0,2,99", luvut.toString()); 
    luvut.set(1,4); assertEquals("From: Taulukko line: 13", "0,4,99", luvut.toString()); 
    int luku = luvut.get(2); 
    assertEquals("From: Taulukko line: 15", 99, luku); 
    assertEquals("From: Taulukko line: 16", 99, luvut.get(2)); 
    try {
    luvut.set(21, 4); 
    fail("Taulukko: 17 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    luvut.lisaa(0); luvut.lisaa(0);  //taulukko täyteen
    try {
    luvut.lisaa(0); 
    fail("Taulukko: 19 Did not throw Taulukko.TaulukkoTaysiException");
    } catch(Taulukko.TaulukkoTaysiException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista106 
   * @throws Taulukko.TaulukkoTaysiException when error
   */
  @Test
  public void testPoista106() throws Taulukko.TaulukkoTaysiException {    // Taulukko: 106
    Taulukko luvut = new Taulukko(7); 
    luvut.lisaa(4); luvut.lisaa(7); luvut.lisaa(9); 
    luvut.lisaa(3); luvut.lisaa(9); luvut.lisaa(2); 
    luvut.poista(9); assertEquals("From: Taulukko line: 112", "4,7,3,2", luvut.toString()); 
    luvut.poista(2); assertEquals("From: Taulukko line: 113", "4,7,3", luvut.toString()); 
    luvut.poista(9); assertEquals("From: Taulukko line: 114", "4,7,3", luvut.toString()); 
    luvut = new Taulukko(9); 
    luvut.lisaa(9); luvut.lisaa(2); luvut.lisaa(9); 
    luvut.lisaa(9); luvut.lisaa(9); luvut.lisaa(9); 
    luvut.lisaa(1); luvut.lisaa(2); luvut.lisaa(3); 
    luvut.poista(9); assertEquals("From: Taulukko line: 119", "2,1,2,3", luvut.toString()); 
    luvut.poista(9); assertEquals("From: Taulukko line: 120", "2,1,2,3", luvut.toString()); 
    luvut.poista(2); assertEquals("From: Taulukko line: 121", "1,3", luvut.toString()); 
  } // Generated by ComTest END
}