package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Demo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.13 20:01:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class DemoTest {



  // Generated by ComTest BEGIN
  /** testDemohyvitys16 */
  @Test
  public void testDemohyvitys16() {    // Demo: 16
    assertEquals("From: Demo line: 17", 5, demohyvitys(5, 6));  //Normaali tapaus
    assertEquals("From: Demo line: 18", 2, demohyvitys(3, 6));  //Tasan sama prosentti
    assertEquals("From: Demo line: 19", 6, demohyvitys(50, 50));  //Kaikki tehty
    assertEquals("From: Demo line: 20", 6, demohyvitys(51, 50));  //On tehty ylimääräistä
    assertEquals("From: Demo line: 21", 6, demohyvitys(49, 50));  //On tehty melkein kaikki
    assertEquals("From: Demo line: 22", 6, demohyvitys(9, 10));  //On tehty 90%
    assertEquals("From: Demo line: 23", 0, demohyvitys(0, 10));  //Ei ole tehty mitään
    assertEquals("From: Demo line: 24", 0, demohyvitys(1, 10));  //On tehty hyvin vähän
    assertEquals("From: Demo line: 25", 6, demohyvitys(-1, 0));  //Maksimipistemäärää ei ole joten saadaan maxhyvitys automaattisesti
    assertEquals("From: Demo line: 26", 6, demohyvitys(2, -1));  //Maksimipistemäärää ei ole joten saadaan maxhyvitys automaattisesti
    assertEquals("From: Demo line: 27", 0, demohyvitys(-1, 10));  //Negatiiviset pisteet
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtumerkki53 */
  @Test
  public void testEtumerkki53() {    // Demo: 53
    assertEquals("From: Demo line: 54", 0, etumerkki(37-36.8, 0.3)); 
    assertEquals("From: Demo line: 55", 1, etumerkki(1, 0.1)); 
    assertEquals("From: Demo line: 56", -1, etumerkki(-1, 0.1)); 
    assertEquals("From: Demo line: 57", 1, etumerkki(1, -0.1)); 
    assertEquals("From: Demo line: 58", 1, etumerkki(1, 0)); 
    assertEquals("From: Demo line: 59", 0, etumerkki(0, 0)); 
    assertEquals("From: Demo line: 60", 0, etumerkki(0, 1)); 
  } // Generated by ComTest END
}