package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Tarkkuus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.13 18:00:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkkuusTest {



  // Generated by ComTest BEGIN
  /** testEtumerkki17 */
  @Test
  public void testEtumerkki17() {    // Tarkkuus: 17
    assertEquals("From: Tarkkuus line: 18", 0, etumerkki(37-36.8, 0.3)); 
    assertEquals("From: Tarkkuus line: 19", 1, etumerkki(1, 0.1)); 
    assertEquals("From: Tarkkuus line: 20", -1, etumerkki(-1, 0.1)); 
    assertEquals("From: Tarkkuus line: 21", 1, etumerkki(1, -0.1)); 
    assertEquals("From: Tarkkuus line: 22", 1, etumerkki(1, 0)); 
    assertEquals("From: Tarkkuus line: 23", 0, etumerkki(0, 0)); 
    assertEquals("From: Tarkkuus line: 24", 0, etumerkki(0, 1)); 
  } // Generated by ComTest END
}