package vk20.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static vk20.Valikoe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.17 14:03:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValikoeTest {



  // Generated by ComTest BEGIN
  /** testKeskiarvo16 */
  @Test
  public void testKeskiarvo16() {    // Valikoe: 16
    assertEquals("From: Valikoe line: 17", 3.0, keskiarvo(new String[]{"Kuusia", "on", "!"}), 0.000001); // Perustapaus
    assertEquals("From: Valikoe line: 18", 0.0, keskiarvo(new String[]{}), 0.000001); // Tyhjä taulukko
    assertEquals("From: Valikoe line: 19", 1.5, keskiarvo(new String[]{"   ", ""}), 0.000001); // Tyhjä merkkijono on 0-pituinen, välilyönti lasketaan merkiksi
  } // Generated by ComTest END
}