package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Pvm.*;
import demo.d3.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.06 18:34:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testPvm23 */
  @Test
  public void testPvm23() {    // Pvm: 23
    assertEquals("From: Pvm line: 24", "12.12.2012", new Pvm(12, 12, 2012).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString36 */
  @Test
  public void testToString36() {    // Pvm: 36
    assertEquals("From: Pvm line: 37", "12.12.2012", new Pvm(12, 12, 2012).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMain48 */
  @Test
  public void testMain48() {    // Pvm: 48
    Pvm p1 = new Pvm(1, 4, 2020); 
    assertEquals("From: Pvm line: 50", "1.4.2020", p1.toString()); 
  } // Generated by ComTest END
}